permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 张帅
  email: edwin.s.zhang@gmail.com
#  link: http://yansu.org
#  weibo: http://weibo.com/yansu0711
  github: http://github.com/z00s

# 站点信息
title: 张帅的博客
description: 张帅的博客
url: http://yansu.org
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://ww3.sinaimg.cn/small/897b1cc3gw1eraxlzl3i3j208207jglq.jpg
favicon: /assets/img/z00s_favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: edwinio