# Site settings
title: Zhang Shuai
email: your-email@domain.com
url: https://example.github.io
description: "zhang shuai"
paginate: 3
paginate_path: "page:num"

# Contact form: comment the line below if you want to stick with the default PHP contact form
#contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Build settings
#markdown: kramdown
#kramdown:
#     input: GFM
#permalink: pretty

#highlighter: pygments
#pygments: true
#markdown: redcarpet
#redcarpet:
# extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]


markdown:      redcarpet
markdown_ext:  markdown,mkd,mkdn,md

redcarpet:
  extensions: [fenced_code_blocks]
  render_options:
#redcarpet:
# extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]